# Exercícios NumPy  

Agora que aprendemos sobre NumPy, vamos testar seu conhecimento. Começaremos com algumas tarefas simples, para depois entrarmos nas perguntas mais complicadas.

#### Importe NumPy como np

In [ ]:
import numpy as np

#### Crie uma matriz de 10 zeros

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crie uma matriz de 10 ones

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crie uma matriz de 10 cincos

In [ ]:
np.ones(10)*5
#np.ones(10) + 4

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crie um array de inteiros de 10 até 50

In [ ]:
np.arange(10, 51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Crie um array dos numeros pares de 10 até 50

In [ ]:
np.arange(10, 51, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Criei uma matriz 3x3 com valores variando de 0 até 8

In [ ]:
arr = np.arange(0, 9).reshape(3,3)
#arr = np.array(([0,1,2],[3,4,5],[6,7,8]))
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Crie uma matriz identidade 3x3

In [ ]:
#arr3 = np.array(([1,0,0],[0,1,0],[0,1,0]))
arr3 = np.eye(3)
print(arr3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy para gerar números aleatórios entre 0 e 1

In [ ]:
np.random.rand(1)

array([0.01376947])

#### Use Numpy para gerar um array de 25 números aleatórios tirados de uma distribuição normal.

In [ ]:
np.random.randn(25)

array([ 0.34769771,  0.18787596, -0.18395281,  1.3518416 , -0.70988594,
       -1.27883885,  0.14123091,  0.6249867 ,  0.59816829, -1.6694367 ,
        1.2242473 , -1.75589116,  1.14615392, -0.79463214, -1.02945892,
        1.07273335,  0.00862897, -1.33708261,  1.69670169,  0.07774372,
        0.55615725, -0.61634322,  0.9585334 , -0.95989181,  0.09538947])

#### Crie a seguinte matriz:

In [ ]:
#np.linspace(0,10,100)
np.arange(0,10) / 100

array([0.  , 0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09])

#### Crie um array de tamanho 20 igualmente espaçado entre 0 e 1.

In [ ]:
arr = np.linspace(0,1,20)
#arr = np.random.rand(4,5)
print(arr)

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


## Indexação Numpy e Seleção

Agora você receberá algumas matrizes e será solicitado a replicar as saídas resultantes da matriz:

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
# SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
# PODE VER A SORTEZA MAIS QUALQUER
mat[2:, 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
# SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
# PODE VER A SORTEZA MAIS QUALQUER

In [ ]:
mat[:3, 1:2]

20

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
# SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
# PODE VER A SORTEZA MAIS QUALQUER
mat[:3, 1:2] # Da linha 0 a 2.

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
# SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
# PODE VER A SORTEZA MAIS QUALQUER
mat[-1,:]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [ ]:
# ESCREVE O CÓDIGO AQUI QUE REPRODICA A SAÍDA DA CÉLULA ABAIXO
# SEJA CUIDADOSO PARA NÃO FUNCIONAR A CÉLULA ABAIXO, DE OUTRA FORMA, NÃO PODERÁ
# PODE VER A SORTEZA MAIS QUALQUER
mat[-2:, :] # Ou mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Agora faça o seguinte

#### Obter a soma de todos os valores no "mat"

In [ ]:
np.sum(mat)
# mat.sum()

325

#### Obter o desvio padrão dos valores em mat

In [ ]:
np.std(mat)

7.211102550927978

#### Obter a soma de todas as colunas em mat

In [ ]:
mat.sum(axis=0) # .sum(axis=0) é soma das colunas e axis=1 é soma das linhas

array([55, 60, 65, 70, 75])